// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6QcoxO6WvCOxFyLmJcrlImTGjfxqdzA',
    appId: '1:980961077426:web:5d6594eef50ad3453dc1ab',
    messagingSenderId: '980961077426',
    projectId: 'chat-app-8dbb3',
    authDomain: 'chat-app-8dbb3.firebaseapp.com',
    storageBucket: 'chat-app-8dbb3.firebasestorage.app',
    measurementId: 'G-2F1DCVPV1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHt60FagzQXKp5B_p-CAN9racG_6u4Xo',
    appId: '1:980961077426:android:740802a0e2c819213dc1ab',
    messagingSenderId: '980961077426',
    projectId: 'chat-app-8dbb3',
    storageBucket: 'chat-app-8dbb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKuAZzqh0foQULse7jqRu9dxZMNiblsw',
    appId: '1:980961077426:ios:113dadc7775725cf3dc1ab',
    messagingSenderId: '980961077426',
    projectId: 'chat-app-8dbb3',
    storageBucket: 'chat-app-8dbb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHKuAZzqh0foQULse7jqRu9dxZMNiblsw',
    appId: '1:980961077426:ios:113dadc7775725cf3dc1ab',
    messagingSenderId: '980961077426',
    projectId: 'chat-app-8dbb3',
    storageBucket: 'chat-app-8dbb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm6QcoxO6WvCOxFyLmJcrlImTGjfxqdzA',
    appId: '1:980961077426:web:5f5a86b4227411ba3dc1ab',
    messagingSenderId: '980961077426',
    projectId: 'chat-app-8dbb3',
    authDomain: 'chat-app-8dbb3.firebaseapp.com',
    storageBucket: 'chat-app-8dbb3.firebasestorage.app',
    measurementId: 'G-FSMVEZHF06',
  );
}
